import { getPresignedUrlsBatch, uploadFileToS3, getPublicUrl } from '../api/mediaApi';
import type { UploadedMedia } from '../api/mediaApi';

export interface UploadProgress {
  fileName: string;
  progress: number;
  status: 'pending' | 'uploading' | 'completed' | 'error';
  error?: string;
}

export class MediaUploadService {
  /**
   * Upload multiple files to S3
   */
  async uploadFiles(
    files: File[],
    onProgress?: (progress: UploadProgress[]) => void
  ): Promise<UploadedMedia[]> {
    if (files.length === 0) {
      return [];
    }

    // Initialize progress tracking
    const progressMap: Map<string, UploadProgress> = new Map();
    files.forEach((file) => {
      progressMap.set(file.name, {
        fileName: file.name,
        progress: 0,
        status: 'pending',
      });
    });

    const updateProgress = () => {
      if (onProgress) {
        onProgress(Array.from(progressMap.values()));
      }
    };

    try {
      // Step 1: Get presigned URLs for all files
      const presignedUrlRequests = files.map((file) => ({
        fileName: file.name,
        fileType: file.type,
        fileSize: file.size,
      }));

      const { urls } = await getPresignedUrlsBatch(presignedUrlRequests);

      // Step 2: Upload files to S3
      const uploadPromises = files.map(async (file, index) => {
        const { uploadUrl, fileKey } = urls[index];
        
        // Update progress to uploading
        const progress = progressMap.get(file.name);
        if (progress) {
          progress.status = 'uploading';
          progress.progress = 0;
          updateProgress();
        }

        try {
          await uploadFileToS3(uploadUrl, file);

          // Update progress to completed
          if (progress) {
            progress.status = 'completed';
            progress.progress = 100;
            updateProgress();
          }

          // Return the uploaded media metadata (fileUrl will be generated by backend)
          return {
            fileKey,
            fileName: file.name,
            fileType: file.type,
            fileSize: file.size,
          };
        } catch (error) {
          // Update progress with error
          if (progress) {
            progress.status = 'error';
            progress.error = error instanceof Error ? error.message : 'Upload failed';
            updateProgress();
          }
          throw error;
        }
      });

      const results = await Promise.all(uploadPromises);
      return results;
    } catch (error) {
      // Mark all pending/uploading files as error
      progressMap.forEach((progress) => {
        if (progress.status !== 'completed') {
          progress.status = 'error';
          progress.error = error instanceof Error ? error.message : 'Upload failed';
        }
      });
      updateProgress();
      throw error;
    }
  }

  /**
   * Validate file before upload
   */
  validateFile(
    file: File,
    maxFileSize: number,
    allowedMimeTypes: { images: string[]; videos: string[] }
  ): { valid: boolean; error?: string } {
    // Check file size
    if (file.size > maxFileSize) {
      const maxSizeMB = (maxFileSize / (1024 * 1024)).toFixed(2);
      return {
        valid: false,
        error: `File size exceeds maximum allowed size of ${maxSizeMB}MB`,
      };
    }

    // Check file type
    const allAllowedTypes = [...allowedMimeTypes.images, ...allowedMimeTypes.videos];
    if (!allAllowedTypes.includes(file.type)) {
      return {
        valid: false,
        error: `File type ${file.type} is not allowed. Only images and videos are supported.`,
      };
    }

    return { valid: true };
  }

  /**
   * Format file size for display
   */
  formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 Bytes';

    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));

    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }

  /**
   * Check if file is an image
   */
  isImageFile(file: File): boolean {
    return file.type.startsWith('image/');
  }

  /**
   * Check if file is a video
   */
  isVideoFile(file: File): boolean {
    return file.type.startsWith('video/');
  }
}

export const mediaUploadService = new MediaUploadService();
